2022-04-28 16:01:01,437 INFO    MainThread:30775 [wandb_setup.py:_flush():69] setting env: {}
2022-04-28 16:01:01,438 INFO    MainThread:30775 [wandb_setup.py:_flush():69] setting login settings: {}
2022-04-28 16:01:01,438 INFO    MainThread:30775 [wandb_init.py:_log_setup():338] Logging user logs to /home/jmj3047/mj_MLP_prac/wandb/run-20220428_160101-nrz5ckn1/logs/debug.log
2022-04-28 16:01:01,438 INFO    MainThread:30775 [wandb_init.py:_log_setup():339] Logging internal logs to /home/jmj3047/mj_MLP_prac/wandb/run-20220428_160101-nrz5ckn1/logs/debug-internal.log
2022-04-28 16:01:01,439 INFO    MainThread:30775 [wandb_init.py:_jupyter_setup():289] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fc387463d90>
2022-04-28 16:01:01,439 INFO    MainThread:30775 [wandb_init.py:init():371] calling init triggers
2022-04-28 16:01:01,440 INFO    MainThread:30775 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {'lr': 0.001, 'model_name': 'MLPWithDropout', 'optimizer_name': 'RAdam', 'scheduler_name': 'no'}
2022-04-28 16:01:01,440 INFO    MainThread:30775 [wandb_init.py:init():391] re-initializing run, found existing run on stack: t8qh92bz
2022-04-28 16:01:01,443 INFO    MainThread:30775 [wandb_run.py:finish():1295] finishing run minjeejang/fastcapmus_fashion_mnist_tutorials/t8qh92bz
2022-04-28 16:01:01,443 INFO    MainThread:30775 [wandb_run.py:_atexit_cleanup():1595] got exitcode: 0
2022-04-28 16:01:01,444 INFO    MainThread:30775 [wandb_run.py:_restore():1567] restore
2022-04-28 16:01:02,390 INFO    MainThread:30775 [wandb_run.py:_restore():1567] restore
2022-04-28 16:01:02,418 ERROR   MainThread:30775 [wandb_init.py:init():788] error
Traceback (most recent call last):
  File "/home/jmj3047/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1603, in _atexit_cleanup
    'wandb.save("/mnt/folder/file.h5", base_path="/mnt")'
  File "/home/jmj3047/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1760, in _on_finish
    )
  File "/home/jmj3047/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 233, in publish_telemetry
    update = summary.update.add()
  File "/home/jmj3047/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 535, in _publish
    item.value_json = json_dumps_safer_history(v)
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jmj3047/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 762, in init
    run._on_attach()
  File "/home/jmj3047/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 408, in init
    filesystem._safe_makedirs(os.path.dirname(settings.log_internal))
  File "/home/jmj3047/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1299, in finish
    self, data_type: str, key: str, value: Dict[Union[int, str], str]
  File "/home/jmj3047/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1612, in _atexit_cleanup
    tel.feature.save = True
  File "/home/jmj3047/anaconda3/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 167, in cleanup
    """Launch backend worker if not running."""
  File "/home/jmj3047/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 835, in join
  File "/home/jmj3047/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 544, in _communicate
    raise NotImplementedError
  File "/home/jmj3047/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 549, in _communicate_async
    run = run or self._run
Exception: The wandb backend process has shutdown
2022-04-28 16:03:18,758 INFO    MainThread:30775 [wandb_setup.py:_flush():69] setting env: {}
2022-04-28 16:03:18,758 INFO    MainThread:30775 [wandb_setup.py:_flush():69] setting login settings: {}
2022-04-28 16:03:18,758 INFO    MainThread:30775 [wandb_init.py:_log_setup():338] Logging user logs to /home/jmj3047/mj_MLP_prac/wandb/run-20220428_160318-262vrq5i/logs/debug.log
2022-04-28 16:03:18,758 INFO    MainThread:30775 [wandb_init.py:_log_setup():339] Logging internal logs to /home/jmj3047/mj_MLP_prac/wandb/run-20220428_160318-262vrq5i/logs/debug-internal.log
2022-04-28 16:03:18,759 INFO    MainThread:30775 [wandb_init.py:init():371] calling init triggers
2022-04-28 16:03:18,759 INFO    MainThread:30775 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {'lr': 0.001, 'model_name': 'MLPWithDropout', 'optimizer_name': 'RAdam', 'scheduler_name': 'no'}
2022-04-28 16:03:18,759 INFO    MainThread:30775 [wandb_init.py:init():391] re-initializing run, found existing run on stack: t8qh92bz
2022-04-28 16:03:18,761 INFO    MainThread:30775 [wandb_run.py:finish():1295] finishing run minjeejang/fastcapmus_fashion_mnist_tutorials/t8qh92bz
2022-04-28 16:03:18,763 INFO    MainThread:30775 [wandb_init.py:init():420] starting backend
2022-04-28 16:03:18,763 INFO    MainThread:30775 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-28 16:03:18,766 INFO    MainThread:30775 [backend.py:ensure_launched():135] starting backend process...
2022-04-28 16:03:18,775 INFO    MainThread:30775 [backend.py:ensure_launched():139] started backend process with pid: 32337
2022-04-28 16:03:18,777 INFO    MainThread:30775 [wandb_init.py:init():425] backend started and connected
2022-04-28 16:03:18,799 INFO    MainThread:30775 [wandb_run.py:_label_probe_notebook():846] probe notebook
2022-04-28 16:03:18,800 INFO    MainThread:30775 [wandb_run.py:_label_probe_notebook():853] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-04-28 16:03:18,800 INFO    MainThread:30775 [wandb_init.py:init():473] updated telemetry
2022-04-28 16:03:18,801 INFO    MainThread:30775 [wandb_init.py:init():492] communicating current version
2022-04-28 16:03:19,852 INFO    MainThread:30775 [wandb_init.py:init():497] got version response upgrade_message: "wandb version 0.12.15 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-04-28 16:03:19,855 INFO    MainThread:30775 [wandb_init.py:init():505] communicating run to backend with 30 second timeout
2022-04-28 16:03:20,123 INFO    MainThread:30775 [wandb_init.py:init():530] starting run threads in backend
2022-04-28 16:03:25,142 INFO    MainThread:30775 [wandb_run.py:_console_start():1625] atexit reg
2022-04-28 16:03:25,143 INFO    MainThread:30775 [wandb_run.py:_redirect():1499] redirect: SettingsConsole.WRAP
2022-04-28 16:03:25,143 INFO    MainThread:30775 [wandb_run.py:_redirect():1536] Wrapping output streams.
2022-04-28 16:03:25,145 INFO    MainThread:30775 [wandb_run.py:_redirect():1560] Redirects installed.
2022-04-28 16:03:25,145 INFO    MainThread:30775 [wandb_init.py:init():555] run started, returning control to user process
